version: '3'
services:
  postgres:
    networks:
      - "boba"     
    build:
      context: ./DATABASE
      dockerfile: Dockerfile
    hostname: postgres
    container_name: employee_db_container
    ports:
      - "5433:5432"
  fastapi_app:
    build:
      context: ./ML
      dockerfile: Dockerfile
    container_name: fastapi_app_container
    ports:
      - "8889:8889"
    depends_on:
      - postgres
  app:
    networks:
      - boba 
    build:
      context: ./APP
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    container_name: app_container
networks:
  boba: 

