server:
  port: 8081

application:
  report-limit: 10

spring:
  datasource:
    # url: jdbc:postgresql://localhost:5433/employee_db
    url: jdbc:postgresql://postgres:5432/employee_db
    username: user
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.gmail.com
    port: 587
    username: rassylsikp@gmail.com
    password: crmc kfrb xzrw hnlm
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true